version: "3.8"

services:
  client: 
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    # environment: 
    #  - NODE_ENV=production

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "solana_faucet"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build: ./api
    command: ["/migrate-tool", "up"]
    env_file: ./api/.env
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
  
  api: 
    build: ./api
    ports:
      - "8080:8080"
    env_file: ./api/.env
    depends_on:
      mysql:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  mysql_data:
