CREATE TABLE faucet_requests (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ip_address VARCHAR(45) NOT NULL,
  wallet_address VARCHAR(64) NOT NULL,
  lamports BIGINT UNSIGNED NOT NULL,
  tx_hash VARCHAR(88),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
